---
- hosts: plex
  vars:
    - plex_url: "https://downloads.plex.tv/plex-media-server/0.9.16.4.1911-ee6e505/plexmediaserver_0.9.16.4.1911-ee6e505_amd64.deb"
    - plex_deb: "/tmp/plex.deb"
    - plex_sha1: "c056838454953857fec2622ddd7350635723c09e"
  tasks:
    - name: download and checksum plex debian package
      get_url: url={{ plex_url }} dest={{ plex_deb }} checksum=sha1:{{ plex_sha1 }}

    - name: install plex
      apt: deb={{ plex_deb }} state=installed

    - name: remove temporary plex debian package
      file: path={{ plex_deb }} state=absent

    - name: start plex service
      service: name=plexmediaserver state=started enabled=yes
