---
- name: install rtorrent
  tags:
    - rtorrent
  apt:
    pkg: rtorrent
    state: installed

- name: create rtorrent user
  tags:
    - rtorrent
  user:
    name: rtorrent
    shell: "/bin/false"
    comment: "rtorrent service user"

- name: create rtorrent configuration
  tags:
    - rtorrent
  template:
    src: rtorrent.rc.j2
    dest: "/home/rtorrent/.rtorrent.rc"
    owner: rtorrent
    group: rtorrent
    mode: 0755

- name: create files, watch, and session directories
  tags:
    - rtorrent
  file:
    path: "{{ item }}"
    state: directory
    owner: rtorrent
    group: rtorrent
    mode: 0755
  with_items:
    - "{{ rtorrent_path_files }}"
    - "{{ rtorrent_path_watch }}"
    - "{{ rtorrent_path_session }}"
