---
- name: install zfsutils-linux
  tags:
    - zfs_exporter
  apt:
    pkg: zfsutils-linux
    state: installed

- name: download and checksum zfs_exporter binary
  tags:
    - zfs_exporter
  get_url:
    url: "{{ zfs_exporter_url }}"
    dest: "/usr/local/bin/zfs_exporter"
    checksum: "sha256:{{ zfs_exporter_sha256 }}"

- name: check if zfs_exporter service exists
  tags:
    - zfs_exporter
  stat:
    path: "/lib/systemd/system/zfs_exporter.service"
  register: checked

- name: stop zfs_exporter service if it exists
  tags:
    - zfs_exporter
  when: checked.stat.exists
  service:
    name: zfs_exporter
    state: stopped

- name: set permissions on zfs_exporter binary
  tags:
    - zfs_exporter
  file:
    path: "/usr/local/bin/zfs_exporter"
    owner: prometheus
    group: prometheus
    mode: 0755

- name: create zfs_exporter systemd unit
  tags:
    - zfs_exporter
  template:
    src: zfs_exporter.service.j2
    dest: "/lib/systemd/system/zfs_exporter.service"

- name: reload systemd configurations
  tags:
    - zfs_exporter
  command: "systemctl daemon-reload"

- name: start zfs_exporter service
  tags:
    - zfs_exporter
  service:
    name: zfs_exporter
    state: started
    enabled: yes
