---
# Version configuration.
node_exporter_url: "https://github.com/prometheus/node_exporter/releases/download/0.12.0rc3/node_exporter-0.12.0rc3.linux-amd64.tar.gz"
node_exporter_sha256: "4674fd685bc33cc26f680c49423114e6ccac5a88f03f6f691ff374892809fb0f"
# Static configuration.
node_exporter_tgz: "/tmp/node_exporter.tgz"
node_exporter_tmp: "/tmp/node_exporter"
