---
- name: install mpd and ncmpcpp
  tags:
    - mpd
  apt:
    pkg: "{{ item }}"
    state: installed
  with_items:
    - mpd
    - ncmpcpp

- name: create mpd configuration
  tags:
    - mpd
  template:
    src: mpd.conf.j2
    dest: "/etc/mpd.conf"

- name: restart mpd
  tags:
    - mpd
  service:
    name: mpd
    state: restarted
