---
# Prometheus version and checksum configuration
prometheus_version: "2.0.0-alpha.2"
prometheus_sha256: "81d494d7fef8d111905024d35af5e31fc8260bac6a9d6b9be4259adba7ee11f1"
# Prometheus configuration and data storage locations
prometheus_config: "/etc/prometheus"
prometheus_data: "/var/lib/prometheus"
# Prometheus jobs configuration
prometheus_jobs:
  - job: "apcupsd"
    targets:
      - "192.168.1.3:9162"
  - job: "node"
    targets:
      - "192.168.1.1:9100"
      - "192.168.1.3:9100"
      - "192.168.1.5:9100"
      - "192.168.1.20:9100"
  - job: "prometheus"
    scrape_interval: "5s"
    targets:
      - "192.168.1.3:9090"
  - job: "unifi"
    targets:
      - "192.168.1.3:9130"
  - job: "zfs"
    targets:
      - "192.168.1.3:9134"
# Static configuration.
prometheus_dir: "prometheus-{{ prometheus_version }}.linux-amd64"
prometheus_tmp: "/tmp/{{ prometheus_dir }}"
prometheus_url: "https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version }}/{{ prometheus_dir }}.tar.gz"
prometheus_tgz: "/tmp/prometheus.tar.gz"
