---
# Prometheus version and checksum configuration
prometheus_version: "1.1.0"
prometheus_sha256: "4f0affabd63f2db6bbd917169c290a42f3573ad11d8e12ef1b1efd27902a2156"
# Prometheus configuration and data storage locations
prometheus_config: "/etc/prometheus"
prometheus_data: "/var/lib/prometheus"
# Prometheus jobs configuration
prometheus_jobs:
  - job: "edgemax"
    targets:
      - "192.168.1.3:9132"
  - job: "node"
    targets:
      - "192.168.1.3:9100"
      - "192.168.1.5:9100"
      - "192.168.1.20:9100"
  - job: "prometheus"
    scrape_interval: "5s"
    targets:
      - "192.168.1.3:9090"
  - job: "rtorrent"
    scrape_interval: "5s"
    targets:
      - "192.168.1.3:9135"
  - job: "unifi"
    targets:
      - "unifi.servnerr.com:9130"
  - job: "zfs"
    targets:
      - "192.168.1.3:9134"
# Static configuration.
prometheus_dir: "prometheus-{{ prometheus_version }}.linux-amd64"
prometheus_tmp: "/tmp/{{ prometheus_dir }}"
prometheus_url: "https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version }}/{{ prometheus_dir }}.tar.gz"
prometheus_tgz: "/tmp/prometheus.tar.gz"
