---
# Prometheus version and checksum configuration
prometheus_version: "1.5.0"
prometheus_sha256: "867e04a78766d3c95d399638bf326b1890117141900cd9730ef61437fd03f9a1"
# Prometheus configuration and data storage locations
prometheus_config: "/etc/prometheus"
prometheus_data: "/var/lib/prometheus"
# Prometheus jobs configuration
prometheus_jobs:
  - job: "apcupsd"
    targets:
      - "192.168.1.3:9162"
  - job: "node"
    targets:
      - "192.168.1.3:9100"
      - "192.168.1.5:9100"
      - "192.168.1.20:9100"
  - job: "prometheus"
    scrape_interval: "5s"
    targets:
      - "192.168.1.3:9090"
  - job: "rtorrent"
    scrape_interval: "5s"
    targets:
      - "192.168.1.3:9135"
  - job: "unifi"
    targets:
      - "192.168.1.3:9130"
  - job: "zfs"
    targets:
      - "192.168.1.3:9134"
# Static configuration.
prometheus_dir: "prometheus-{{ prometheus_version }}.linux-amd64"
prometheus_tmp: "/tmp/{{ prometheus_dir }}"
prometheus_url: "https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version }}/{{ prometheus_dir }}.tar.gz"
prometheus_tgz: "/tmp/prometheus.tar.gz"
