---
# Prometheus version and checksum configuration
prometheus_version: "2.2.1"
prometheus_sha256: "ec1798dbda1636f49d709c3931078dc17eafef76c480b67751aa09828396cf31"
# Prometheus configuration and data storage locations
prometheus_config: "/etc/prometheus"
prometheus_data: "/var/lib/prometheus"
# Prometheus jobs configuration
prometheus_jobs:
  - job: "apcupsd"
    targets:
      - "192.168.1.4:9162"
  - job: "arris"
    targets:
      - "192.168.100.1"
    relabel_target: "192.168.1.4:9393"
  - job: "hdhomerun"
    targets:
      - "192.168.1.8"
    relabel_target: "192.168.1.4:9137"
  - job: "node"
    targets:
      - "192.168.1.1:9100"
      - "192.168.1.4:9100"
      - "192.168.1.5:9100"
  - job: "prometheus"
    scrape_interval: "5s"
    targets:
      - "192.168.1.4:9090"
  - job: "traefik"
    targets:
      - "192.168.1.4:8080"
# Static configuration.
prometheus_dir: "prometheus-{{ prometheus_version }}.linux-amd64"
prometheus_tmp: "/tmp/{{ prometheus_dir }}"
prometheus_url: "https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version }}/{{ prometheus_dir }}.tar.gz"
prometheus_tgz: "/tmp/prometheus.tar.gz"
