---
- name: check if prometheus service exists
  tags:
    - prometheus
  stat: path=/etc/init/prometheus.conf
  register: installed

- name: download and checksum prometheus tarball
  tags:
    - prometheus
  when: installed|failed
  get_url: url={{ prometheus_url }} dest={{ prometheus_tgz }} checksum=sha1:{{ prometheus_sha1 }}

- name: unpack prometheus tarball
  tags:
    - prometheus
  when: installed|failed
  unarchive: src={{ prometheus_tgz }} dest=/tmp/ copy=no

- name: create prometheus user
  tags:
    - prometheus
  user: name=prometheus shell=/bin/false comment="prometheus service user"

- name: copy prometheus binary to /usr/local/bin
  tags:
    - prometheus
  when: installed|failed
  copy: src={{ prometheus_tmp }}/prometheus dest=/usr/local/bin/ owner=prometheus group=prometheus mode=0755

- name: copy promtool binary to /usr/local/bin
  tags:
    - prometheus
  when: installed|failed
  copy: src={{ prometheus_tmp }}/promtool dest=/usr/local/bin/ owner=prometheus group=prometheus mode=0755

- name: create prometheus config directory
  tags:
    - prometheus
  file: path={{ prometheus_config }} state=directory owner=prometheus group=prometheus mode=0755

- name: create prometheus configuration
  tags:
    - prometheus
  template: src=prometheus.yml.j2 dest={{ prometheus_config }}/prometheus.yml
  with_items: "{{ prometheus_jobs }}"

- name: create prometheus data directory
  tags:
    - prometheus
  file: path={{ prometheus_data }} state=directory owner=prometheus group=prometheus mode=0755

- name: create prometheus upstart job
  tags:
    - prometheus
  template: src=prometheus.conf.j2 dest=/etc/init/prometheus.conf

- name: restart prometheus service
  tags:
    - prometheus
  # Do not report restarting prometheus as a change; only report config changes
  changed_when: false
  service: name=prometheus state=restarted enabled=yes

- name: remove temporary prometheus directory
  tags:
    - prometheus
  when: installed|failed
  file: path={{ prometheus_tmp }} state=absent

- name: remove temporary prometheus tarball
  tags:
    - prometheus
  when: installed|failed
  file: path={{ prometheus_tgz }} state=absent
