---
- name: install lmsensors
  tags:
    - lmsensors_exporter
  apt:
    pkg: lm-sensors
    state: installed

- name: download and checksum lmsensors_exporter {{ lmsensors_exporter_version }} binary
  tags:
    - lmsensors_exporter
  get_url:
    url: "{{ lmsensors_exporter_url }}"
    dest: "/tmp/lmsensors_exporter"
    checksum: "sha256:{{ lmsensors_exporter_sha256 }}"

- name: create lmsensors_exporter user
  tags:
    - lmsensors_exporter
  user:
    name: lmsensors_exporter
    shell: "/bin/false"
    comment: "lmsensors_exporter service user"

- name: check if lmsensors_exporter service exists
  tags:
    - lmsensors_exporter
  stat:
    path: "/lib/systemd/system/lmsensors_exporter.service"
  register: checked

- name: stop lmsensors_exporter service if it exists
  tags:
    - lmsensors_exporter
  when: checked.stat.exists
  service:
    name: lmsensors_exporter
    state: stopped

- name: copy lmsensors_exporter binary to /usr/local/bin
  tags:
    - lmsensors_exporter
  command: "cp /tmp/lmsensors_exporter /usr/local/bin/"

- name: set permissions on lmsensors_exporter binary
  tags:
    - lmsensors_exporter
  file:
    path: "/usr/local/bin/lmsensors_exporter"
    owner: lmsensors_exporter
    group: lmsensors_exporter
    mode: 0755

- name: create lmsensors_exporter systemd unit
  tags:
    - lmsensors_exporter
  template:
    src: lmsensors_exporter.service.j2
    dest: "/lib/systemd/system/lmsensors_exporter.service"

- name: reload systemd configurations
  tags:
    - lmsensors_exporter
  command: "systemctl daemon-reload"

- name: start lmsensors_exporter service
  tags:
    - lmsensors_exporter
  service:
    name: lmsensors_exporter
    state: started
    enabled: yes

- name: remove temporary files
  tags:
    - lmsensors_exporter
  file:
    path: "/tmp/lmsensors_exporter"
    state: absent
